#ifndef SNIFFLIB_GLOBAL_H
#define SNIFFLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SNIFFLIB_LIBRARY)
#  define SNIFFLIBSHARED_EXPORT Q_DECL_EXPORT
#  define SNIFFLIB_EXPORT Q_DECL_EXPORT
#else
#  define SNIFFLIBSHARED_EXPORT Q_DECL_IMPORT
#  define SNIFFLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // SNIFFLIB_GLOBAL_H
