/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Tue Mar 21 10:29:54 2017. */

#include "zc.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t WIO_INFO_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, WIO_INFO, MacAddr, MacAddr, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, WIO_INFO, Label, MacAddr, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, WIO_INFO, CktType, Label, 0),
    PB_LAST_FIELD
};

const pb_field_t TIMER_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, TIMER, ID, ID, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, TIMER, Duration, ID, 0),
    PB_LAST_FIELD
};

const pb_field_t LOCAL_OUTPUT_CORR_fields[6] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, LOCAL_OUTPUT_CORR, IptCorrs, IptCorrs, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, LOCAL_OUTPUT_CORR, StatCorrs, IptCorrs, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, LOCAL_OUTPUT_CORR, TrbCorrs, StatCorrs, 0),
    PB_FIELD(  4, STRING  , REQUIRED, CALLBACK, OTHER, LOCAL_OUTPUT_CORR, RemTrbCorrs, TrbCorrs, 0),
    PB_FIELD(  5, STRING  , REQUIRED, CALLBACK, OTHER, LOCAL_OUTPUT_CORR, RemIptCorrs, RemTrbCorrs, 0),
    PB_LAST_FIELD
};

const pb_field_t REMOTE_OUTPUT_CORR_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, REMOTE_OUTPUT_CORR, IptCorrs, IptCorrs, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, REMOTE_OUTPUT_CORR, StatCorrs, IptCorrs, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, REMOTE_OUTPUT_CORR, RemIptCorrs, StatCorrs, 0),
    PB_LAST_FIELD
};

const pb_field_t PASSWORD_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, PASSWORD, Len, Len, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, PASSWORD, Data, Len, 0),
    PB_LAST_FIELD
};

const pb_field_t CFG_DST_fields[12] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, CFG_DST, StartMonth, StartMonth, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, StartOrdinalWeek, StartMonth, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, StartDayOfWeek, StartOrdinalWeek, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, StartHour, StartDayOfWeek, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, StartMin, StartHour, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, EndMonth, StartMin, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, EndOrdinalWeek, EndMonth, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, EndDayOfWeek, EndOrdinalWeek, 0),
    PB_FIELD(  9, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, EndHour, EndDayOfWeek, 0),
    PB_FIELD( 10, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, EndMin, EndHour, 0),
    PB_FIELD( 11, INT32   , REQUIRED, STATIC  , OTHER, CFG_DST, DailyAdjust, EndMin, 0),
    PB_LAST_FIELD
};

const pb_field_t ZC_fields[14] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, ZC, Label, Label, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, ZC, GUID, Label, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, ZC, ConfigVer, GUID, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, ZC, gSCUFeatureFlags, ConfigVer, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, ZC, gHWUStrobesType, gSCUFeatureFlags, 0),
    PB_FIELD(  6, STRING  , REQUIRED, CALLBACK, OTHER, ZC, IptCktProcessType, gHWUStrobesType, 0),
    PB_FIELD(  7, MESSAGE , REQUIRED, STATIC  , OTHER, ZC, LocalCorr, IptCktProcessType, &LOCAL_OUTPUT_CORR_fields),
    PB_FIELD(  8, MESSAGE , REQUIRED, STATIC  , OTHER, ZC, Dst, LocalCorr, &CFG_DST_fields),
    PB_FIELD(  9, INT32   , REQUIRED, STATIC  , OTHER, ZC, DataIntCheck, Dst, 0),
    PB_FIELD( 10, MESSAGE , REPEATED, CALLBACK, OTHER, ZC, RemoteCorr, DataIntCheck, &REMOTE_OUTPUT_CORR_fields),
    PB_FIELD( 11, MESSAGE , REPEATED, CALLBACK, OTHER, ZC, Timers, RemoteCorr, &TIMER_fields),
    PB_FIELD( 12, MESSAGE , REPEATED, CALLBACK, OTHER, ZC, WIOInfo, Timers, &WIO_INFO_fields),
    PB_FIELD( 13, MESSAGE , REPEATED, CALLBACK, OTHER, ZC, Password, WIOInfo, &PASSWORD_fields),
    PB_LAST_FIELD
};

const pb_field_t PASSWORDS_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, PASSWORDS, Password, Password, &PASSWORD_fields),
    PB_LAST_FIELD
};

const pb_field_t CFG_RTC_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, CFG_RTC, seconds, seconds, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, CFG_RTC, minutes, seconds, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, CFG_RTC, hours, minutes, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, CFG_RTC, date, hours, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, CFG_RTC, month, date, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, CFG_RTC, year, month, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ZC, LocalCorr) < 65536 && pb_membersize(ZC, Dst) < 65536 && pb_membersize(ZC, RemoteCorr) < 65536 && pb_membersize(ZC, Timers) < 65536 && pb_membersize(ZC, WIOInfo) < 65536 && pb_membersize(ZC, Password) < 65536 && pb_membersize(PASSWORDS, Password) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_WIO_INFO_TIMER_LOCAL_OUTPUT_CORR_REMOTE_OUTPUT_CORR_PASSWORD_CFG_DST_ZC_PASSWORDS_CFG_RTC)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ZC, LocalCorr) < 256 && pb_membersize(ZC, Dst) < 256 && pb_membersize(ZC, RemoteCorr) < 256 && pb_membersize(ZC, Timers) < 256 && pb_membersize(ZC, WIOInfo) < 256 && pb_membersize(ZC, Password) < 256 && pb_membersize(PASSWORDS, Password) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_WIO_INFO_TIMER_LOCAL_OUTPUT_CORR_REMOTE_OUTPUT_CORR_PASSWORD_CFG_DST_ZC_PASSWORDS_CFG_RTC)
#endif


/* @@protoc_insertion_point(eof) */
